config/routes.rb
Naturesoft::Locations::Engine.routes.draw do
  namespace :backend, module: "backend", path: "backend/locations" do
    resources :locations do
      collection do
        put "enable"
        put "disable"
        delete "delete"
      end
    end
  end
end

app/models/naturesoft/locations/application_record.rb
module Naturesoft::Locations
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/naturesoft/locations/location.rb
module Naturesoft::Locations
  class Location < ApplicationRecord
    belongs_to :user
    belongs_to :area, class_name: "Naturesoft::Areas::Area"
    
    validates :name, :longitude, :latitude, presence: true
    
    def self.sort_by
      [
        ["Name","naturesoft_locations_locations.name"],
        ["Created At","naturesoft_locations_locations.created_at"]
      ]
    end
    def self.sort_orders
      [
        ["ASC","asc"],
        ["DESC","desc"]
      ]
    end
    
    #Filter, Sort
    def self.search(params)
      records = self.all
      
      if params[:scale].present?
        records = records.where(image_scale: params[:scale])
      end
      
      #Search keyword filter
      if params[:keyword].present?
        params[:keyword].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_locations_locations.name,' ',naturesoft_locations_locations.longitude,' ',naturesoft_locations_locations.latitude)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end
      
      # for sorting
      sort_by = params[:sort_by].present? ? params[:sort_by] : "naturesoft_locations_locations.name"
      sort_orders = params[:sort_orders].present? ? params[:sort_orders] : "asc"
      records = records.order("#{sort_by} #{sort_orders}")
      
      return records
    end
    
    # enable/disable status
    def enable
			update_columns(status: "active")
		end
    
    def disable
			update_columns(status: "inactive")
		end
    
  end
end

app/controllers/naturesoft/locations/admin/locations_controller.rb
require_dependency "naturesoft/application_controller"

module Naturesoft
  module Locations
    module Admin
      class LocationsController < Naturesoft::Admin::AdminController
        before_action :set_location, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Location", naturesoft_locations.admin_locations_path
        end
    
        # GET /locations
        def index
          @locations = Location.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /locations/1
        def show
        end
    
        # GET /locations/new
        def new
          @location = Location.new
          add_breadcrumb "New Location", nil,  class: "active"
        end
    
        # GET /locations/1/edit
        def edit
          add_breadcrumb "Edit Location", nil,  class: "active"
        end
    
        # POST /locations
        def create
          @location = Location.new(location_params)
          @location.user = current_user
    
          if @location.save
            redirect_to naturesoft_locations.edit_admin_location_path(@location.id), notice: 'Location was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /locations/1
        def update
          if @location.update(location_params)
            redirect_to naturesoft_locations.edit_admin_location_path(@location.id), notice: 'Location was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /locations/1
        def destroy
          @location.destroy
          render text: 'Location was successfully destroyed.'
        end
        
        #CHANGE STATUS /locations
        def enable
          @location.enable
          render text: 'Location was successfully active.'
        end
        
        def disable
          @location.disable
          render text: 'Location was successfully inactive.'
        end
        
        # DELETE /locations/delete?ids=1,2,3
        def delete
          @locations = Location.where(id: params[:ids].split(","))
          @locations.destroy_all
          render text: 'Location(s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_location
            @location = Location.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def location_params
            params.fetch(:location, {}).permit(:name, :longitude, :latitude, :area_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/locations/backend/locations_controller.rb
require_dependency "naturesoft/application_controller"

module Naturesoft
  module Locations
    module Backend
      class LocationsController < Naturesoft::Backend::BackendController
        before_action :set_location, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Location", naturesoft_locations.backend_locations_path
        end
    
        # GET /locations
        def index
          @locations = Location.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /locations/1
        def show
        end
    
        # GET /locations/new
        def new
          @location = Location.new
          add_breadcrumb "New Location", nil,  class: "active"
        end
    
        # GET /locations/1/edit
        def edit
          add_breadcrumb "Edit Location", nil,  class: "active"
        end
    
        # POST /locations
        def create
          @location = Location.new(location_params)
          @location.user = current_user
    
          if @location.save
            redirect_to naturesoft_locations.edit_backend_location_path(@location.id), notice: 'Location was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /locations/1
        def update
          if @location.update(location_params)
            redirect_to naturesoft_locations.edit_backend_location_path(@location.id), notice: 'Location was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /locations/1
        def destroy
          @location.destroy
          render text: 'Location was successfully destroyed.'
        end
        
        #CHANGE STATUS /locations
        def enable
          @location.enable
          render text: 'Location was successfully active.'
        end
        
        def disable
          @location.disable
          render text: 'Location was successfully inactive.'
        end
        
        # DELETE /locations/delete?ids=1,2,3
        def delete
          @locations = Location.where(id: params[:ids].split(","))
          @locations.destroy_all
          render text: 'Location(s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_location
            @location = Location.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def location_params
            params.fetch(:location, {}).permit(:name, :longitude, :latitude, :area_id)
          end
      end
    end
  end
end

app/helpers/naturesoft/locations/application_helper.rb
module Naturesoft
  module Locations
    module ApplicationHelper
    end
  end
end

app/views/layouts/naturesoft/locations/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locations</title>
  <%= stylesheet_link_tag    "naturesoft/locations/application", media: "all" %>
  <%= javascript_include_tag "naturesoft/locations/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/naturesoft/locations/admin/locations/_form.html.erb
<% if location.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this slideshow from being saved:</h2>
  
      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="panel panel-flat">
  
  <div class="panel-body">
    
    <%= form_for([naturesoft_locations, :admin, location], html: {class: "form-horizontal", id: "validate_checking"}) do |f| %>
      
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:name) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :name, class: "form-control required" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:area) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <div class="input-group">
                  <% selected = options_for_select([[location.area.name, location.area_id]], location.area_id) if location.area.present? %>
                  <%= select_tag("location[area_id]",
                    selected,
                    {
                      class: "select2-ajax required",
                      include_blank: "none",
                      "data-url": naturesoft_areas.select2_admin_areas_path,
                    }
                  ) %>
                  <span class="input-group-btn">
                    <a class="btn btn-info" href="<%= naturesoft_areas.new_admin_area_path %>"><i class="icon-plus2"></i></a>
                  </span>
              </div>
            </div>
          </div>
        </div>
      </div>
        
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:longitude) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :longitude, class: "form-control required" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:latitude) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :latitude, class: "form-control required" %>
            </div>
          </div>
        </div>
      </div>
    
      <div class="text-right">
        <%= button_tag "#{t(:save)}<i class=\"icon-check position-right\"></i>".html_safe, class: "btn btn-primary"%>
        <%= link_to "#{t(:cancel)}<i class=\"icon-cross3 position-right\"></i>".html_safe, naturesoft_locations.admin_locations_path, class: "btn btn-danger"%>
      </div>
        
    <% end %>
  </div>
</div>

app/views/naturesoft/locations/admin/locations/index.html.erb
<% title t(:locations) %>

<div class="page_actions">
    <%= link_to "#{t(:new_location)} <i class=\"icon-plus22 position-right\"></i>".html_safe, naturesoft_locations.new_admin_location_path, class: 'btn btn-primary' %>
</div>
<br />

<form class="listing-form">
    
    <div class="panel panel-flat border-top-primary">
        <div class="panel-body filter-box">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label><%= t(:sort_by) %></label>
                        <%= select_tag(:sort_by, options_for_select(Naturesoft::Locations::Location.sort_by, :selected => params[:sort_by]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label><%= t(:sort_orders) %></label>
                        <%= select_tag(:sort_orders, options_for_select(Naturesoft::Locations::Location.sort_orders, :selected => params[:sort_orders]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group has-feedback">
                        <label><%= t(:search) %></label>
                        <input type="text" name="keyword" class="form-control" placeholder="Enter search..." value="<%= params[:keyword] %>">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-size-base"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            
    <div class="btn-group list_actions mb-10 hide">
        <button type="button" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown">
            Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">											
            <li>
                <a href="" data-href="<%= naturesoft_locations.delete_admin_locations_path %>" data-confirm="Are you sure!" data-method="DELETE">
                    <i class="icon-enter"></i> Delete
                </a>
            </li>            
        </ul>
    </div>
                
    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="table-container">
            <table class="table">
                <thead>
                    <tr class="bg-teal-800">
                        <th width="1%" class="check_all_list">
                            <input type="checkbox" class="styled">
                        </th>
                        <th><%= t(:name) %></th>
                        <th><%= t(:coordinate) %></th>
                        <th><%= t(:created_at) %></th>
                        <th><%= t(:status) %></th>
                        <th class="text-right"><%= t(:actions) %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @locations.each do |item| %>
                        <tr<% if item.status == "active" %> class="success"<% else %> class="warning"<% end %>>
                            <td width="1%">
                                <input type="checkbox" class="node styled"
                                    name="ids[]"
                                    value="<%= item.id %>"
                                />
                            </td>
                            <td class="kq_search">
                              <strong><%= link_to item.name, naturesoft_locations.edit_admin_location_path(item) %></strong>
                            </td>
                            <td class="kq_search">
                              <%= item.longitude %><br /><%= item.latitude %>
                            </td>
                            <td><%= item.created_at.strftime("%d/%m/%Y") %></td>
                            <td><%= display_status(item.status) %></td>
                            <td class="text-right">
                              <div class="btn-group">
                                <%= link_to '<i class="icon-pencil"></i>'.html_safe, naturesoft_locations.edit_admin_location_path(item), class: "btn bg-teal btn-icon btn-xs", title: item.name %>
                                <button type="button" class="btn bg-teal dropdown-toggle btn-xs" data-toggle="dropdown"><span class="caret"></span></button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <% if item.status == "active" %>
                                    <li>
                                        <%= link_to '<i class="icon-lock4"></i> '.html_safe + t(:inactive), naturesoft_locations.disable_admin_locations_path(id: item.id), method: :put %>
                                    </li>
                                    <% end %>
                                    <% if item.status == "inactive" %>
                                    <li>
                                        <%= link_to '<i class="icon-unlocked"></i> '.html_safe + t(:active), naturesoft_locations.enable_admin_locations_path(id: item.id), method: :put %>
                                    </li>
                                    <% end %>
                                    <li>
                                        <%= link_to '<i class="icon-cross2"></i> '.html_safe + t(:delete), naturesoft_locations.admin_location_path(item), method: :delete, data: {confirm: 'Are you sure?'} %>
                                    </li>
                                  </ul>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="dataTables_wrapper no-footer">
                <div class="datatable-footer showed">
                    <div class="dataTables_info" ><%= page_entries_info @locations %></div>
                    <div class="dataTables_paginate paging_simple_numbers">
                        <%= will_paginate @locations, previous_label: '←', next_label: '→', renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- /basic datatable -->

app/views/naturesoft/locations/backend/locations/_form.html.erb
<% if location.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this slideshow from being saved:</h2>
  
      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="panel panel-flat">
  
  <div class="panel-body">
    
    <%= form_for([naturesoft_locations, :backend, location], html: {class: "form-horizontal", id: "validate_checking"}) do |f| %>
      
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:name) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :name, class: "form-control required" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:area) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <div class="input-group">
                  <% selected = options_for_select([[location.area.name, location.area_id]], location.area_id) if location.area.present? %>
                  <%= select_tag("location[area_id]",
                    selected,
                    {
                      class: "select2-ajax required",
                      include_blank: "none",
                      "data-url": naturesoft_areas.select2_backend_areas_path,
                    }
                  ) %>
                  <span class="input-group-btn">
                    <a class="btn btn-info" href="<%= naturesoft_areas.new_backend_area_path %>"><i class="icon-plus2"></i></a>
                  </span>
              </div>
            </div>
          </div>
        </div>
      </div>
        
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:longitude) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :longitude, class: "form-control required" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-md-12 control-label" ><%= t(:latitude) %> <span class='text-danger'>*</span></label>
            <div class="col-md-12">
              <%= f.text_field :latitude, class: "form-control required" %>
            </div>
          </div>
        </div>
      </div>
    
      <div class="text-right">
        <%= button_tag "#{t(:save)}<i class=\"icon-check position-right\"></i>".html_safe, class: "btn btn-primary"%>
        <%= link_to "#{t(:cancel)}<i class=\"icon-cross3 position-right\"></i>".html_safe, naturesoft_locations.backend_locations_path, class: "btn btn-danger"%>
      </div>
        
    <% end %>
  </div>
</div>

app/views/naturesoft/locations/backend/locations/edit.html.erb
<% title t(:edit_location) %>

<%= render 'form', location: @location %>

app/views/naturesoft/locations/backend/locations/index.html.erb
<% title t(:locations) %>

<div class="page_actions">
    <%= link_to "#{t(:new_location)} <i class=\"icon-plus22 position-right\"></i>".html_safe, naturesoft_locations.new_backend_location_path, class: 'btn btn-primary' %>
</div>
<br />

<form class="listing-form">
    
    <div class="panel panel-flat border-top-primary">
        <div class="panel-body filter-box">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label><%= t(:sort_by) %></label>
                        <%= select_tag(:sort_by, options_for_select(Naturesoft::Locations::Location.sort_by, :selected => params[:sort_by]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label><%= t(:sort_orders) %></label>
                        <%= select_tag(:sort_orders, options_for_select(Naturesoft::Locations::Location.sort_orders, :selected => params[:sort_orders]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group has-feedback">
                        <label><%= t(:search) %></label>
                        <input type="text" name="keyword" class="form-control" placeholder="Enter search..." value="<%= params[:keyword] %>">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-size-base"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            
    <div class="btn-group list_actions mb-10 hide">
        <button type="button" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown">
            Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">											
            <li>
                <a href="" data-href="<%= naturesoft_locations.delete_backend_locations_path %>" data-confirm="Are you sure!" data-method="DELETE">
                    <i class="icon-enter"></i> Delete
                </a>
            </li>            
        </ul>
    </div>
                
    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="table-container">
            <table class="table">
                <thead>
                    <tr class="bg-teal-800">
                        <th width="1%" class="check_all_list">
                            <input type="checkbox" class="styled">
                        </th>
                        <th><%= t(:name) %></th>
                        <th><%= t(:coordinate) %></th>
                        <th><%= t(:created_at) %></th>
                        <th><%= t(:status) %></th>
                        <th class="text-right"><%= t(:actions) %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @locations.each do |item| %>
                        <tr<% if item.status == "active" %> class="success"<% else %> class="warning"<% end %>>
                            <td width="1%">
                                <input type="checkbox" class="node styled"
                                    name="ids[]"
                                    value="<%= item.id %>"
                                />
                            </td>
                            <td class="kq_search">
                              <strong><%= link_to item.name, naturesoft_locations.edit_backend_location_path(item) %></strong>
                            </td>
                            <td class="kq_search">
                              <%= item.longitude %><br /><%= item.latitude %>
                            </td>
                            <td><%= item.created_at.strftime("%d/%m/%Y") %></td>
                            <td><%= display_status(item.status) %></td>
                            <td class="text-right">
                              <div class="btn-group">
                                <%= link_to '<i class="icon-pencil"></i>'.html_safe, naturesoft_locations.edit_backend_location_path(item), class: "btn bg-teal btn-icon btn-xs", title: item.name %>
                                <button type="button" class="btn bg-teal dropdown-toggle btn-xs" data-toggle="dropdown"><span class="caret"></span></button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <% if item.status == "active" %>
                                    <li>
                                        <%= link_to '<i class="icon-lock4"></i> '.html_safe + t(:inactive), naturesoft_locations.disable_backend_locations_path(id: item.id), method: :put %>
                                    </li>
                                    <% end %>
                                    <% if item.status == "inactive" %>
                                    <li>
                                        <%= link_to '<i class="icon-unlocked"></i> '.html_safe + t(:active), naturesoft_locations.enable_backend_locations_path(id: item.id), method: :put %>
                                    </li>
                                    <% end %>
                                    <li>
                                        <%= link_to '<i class="icon-cross2"></i> '.html_safe + t(:delete), naturesoft_locations.backend_location_path(item), method: :delete, data: {confirm: 'Are you sure?'} %>
                                    </li>
                                  </ul>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="dataTables_wrapper no-footer">
                <div class="datatable-footer showed">
                    <div class="dataTables_info" ><%= page_entries_info @locations %></div>
                    <div class="dataTables_paginate paging_simple_numbers">
                        <%= will_paginate @locations, previous_label: '←', next_label: '→', renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- /basic datatable -->

app/views/naturesoft/locations/backend/locations/new.html.erb
<% title t(:new_location) %>

<%= render 'form', location: @location %>

app/views/naturesoft/locations/backend/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/naturesoft/locations/overrides/_backend_locations_link.html.erb
<li>
  <a href="#"><i class="fa fa-location-arrow"></i> <span><%= t(:location) %></span></a>
  <ul>
      <li>
        <%= link_to 'Locations', naturesoft_locations.backend_locations_path %>
      </li>
  </ul>
</li>